### ISSUE TITLE
Mistakes in definitions

### ISSUE THREAD

**Issue by gasyoun** [sanskrit-lexicon/PWG#27] opened 2017-07-28 13:01 UTC
* https://groups.google.com/forum/#!topic/bvparishat/ntuaembSOsg

**Comment by funderburkjim** [comment] 2017-08-02 23:00
The comment above indicates disdain for European studies of Sanskrit.  I have seen this sentiment occasionally elsewhere, but am uncertain of its origins or of how representative it is of the thoughts of Indian scholars.

**Comment by drdhaval2785** [comment] 2020-12-14 09:58
We can not do much in case a lexicographer gave X or Y meaning to a word. It is for scholars to debate truth or otherwise of it. As a digitization project, our job is to reproduce the meaning as given in the text (except in cases of confirmed print error). 
So closing this.

**Closed by drdhaval2785** 2020-12-14 09:58 UTC
Labels: wontfix

**Comment by funderburkjim** [comment] 2020-12-14 19:38
> We can not ...

Definitely agree.  It is a bedrock of the current  role of sanskrit-lexicon,
and has been so since inception with Peter, Thomas and Malcolm .

**Comment by gasyoun** [comment] 2020-12-14 22:24
> since inception with Peter, Thomas and Malcolm

The Holy Trinity.
